### PR TITLE
Add Install instructions

### PR DESCRIPTION
**Pull request by pedromorgan**
This caught me out, so editing directly

### CODE REVIEW

**Comment by anonx** [comment]
@pedromorgan Shouldn't you target `develop` branch?

**Comment by pedromorgan** [comment]
no.. might as well get straight into master

**Comment by notzippy** [comment]
You should add a note saying dependent go libraries will be downloaded automatically when revel is first launched.

**Comment by brendensoares** [comment]
I would remove `bash` since it will work in other shells, too. This is a good addition, though!

**Comment by pedromorgan** [comment]
So sh instead..

Also need to explain deps insatll

**Comment by brendensoares** [comment]
@pedromorgan I wouldn't mention shell at all, just "command line" since Windows doesn't have shells.

Note how we currently document important commands: https://revel.github.io/tutorial/gettingstarted.html

**Comment by brendensoares** [comment]
@pedromorgan on 2nd thought, please retarget to `develop` branch. @anonx  is right, we need to be consistent with our dev workflow across all repos.

**Pull request merged**
