### PR TITLE
Install package dependencies when building

### PR DESCRIPTION
**Pull request by ottob**
This speeds up recurring compilations a lot.

### CODE REVIEW

**Comment by tike** [comment]
I like that a lot, revel's building can be quite slow'ish on larger projects!

**Comment by jeevatkm** [comment]
@ottob thanks for contributing to Revel! please target the `develop` branch per [Revel's Contributing Guidelines](https://github.com/revel/revel/blob/master/CONTRIBUTING.md#how-revel-is-developed).

Did you get chance to verify with subsequent builds while developing?

**Comment by ottob** [comment]
Correct branch now I hope. Yes, I have verified that subsequent builds are faster.

**Comment by jeevatkm** [comment]
@ottob thanks. I see your two more changes you have pushed. I think its still pointing to `revel/cmd:master`.

I hope this link might be help https://help.github.com/articles/using-pull-requests/#changing-the-branch-range-and-destination-repository

**Comment by ottob** [comment]
Replaced by https://github.com/revel/cmd/pull/43

**Pull request closed without merging**
