### PR TITLE
add build minify command

### PR DESCRIPTION
**Pull request by weidewang**
build minify revel project,remove all *.go file and empey directory.

### CODE REVIEW

**Comment by notzippy** [comment]
Hi, how does this compare to pr #44 ? Which approach do you like better ?

**Comment by weidewang** [comment]
Hi,

#44 is a great idea. In addition, when deploying the revel project, if the relative path of the log is configured in the app.conf, the directory level of the log will be deeper, which is not convenient for the management of the log.

So, in this branch, simply delete all.Go files, but also modify the directory structure, the transfer of -importPath and -srcPath to the root directory, relative to the project, the log directory to the root directory of the project.

**Comment by notzippy** [comment]
@rami-dabain If you want to skip a folder, start the folder name with a period. Revel will then skip those files in that folder when packaging and building

**Comment by notzippy** [comment]
Closing this as this was implemented in the new build

**Pull request closed without merging**
