### PR TITLE
fix issue where websockets don't work with SSL in dev mode.

### PR DESCRIPTION
**Pull request by mattbaird**
As the comment says, it's ok to skip the verify on the cert since
this proxy is only used in dev mode.

### CODE REVIEW

**Comment by mattbaird** [comment]
this is a non controversial patch, should be easy to merge.

**Comment by DavidHunter** [comment]
I think they are removing support for this. [Remove HTTPS from Revel](https://github.com/revel/revel/issues/549)

**Comment by brendensoares** [comment]
Sorry, but can you please target `develop`? This is indeed a simple merge when it's ready. Thanks.

**Comment by brendensoares** [comment]
@mattbaird ping?

**Comment by jeevatkm** [comment]
Manually targeted and merged to develop branch.

**Pull request closed without merging**
