### PR TITLE
Switch to revel.Walk, the symlink-aware filepath.Walk helper

### PR DESCRIPTION
**Pull request by metafex**
This changes filepath.Walk to the revel.Walk helper from https://github.com/revel/revel/pull/867.

### CODE REVIEW

**Comment by brendensoares** [comment]
:+1: pending revel/revel#867 testing.

Thanks!

**Comment by pedromorgan** [comment]
Can we create test for this  and merge ?

**Comment by brendensoares** [comment]
@pedromorgan we need to do manual testing with symbolic links in the file structure to prove that this works as expected. You're welcome to do that or anyone else on @revel/core can do the same.

My time is very limited right now and I am struggling to stay on top of these new code changes by myself. I need help.

**Comment by xoen** [comment]
I think this is causing this issue for me: https://github.com/revel/cmd/issues/53 ~ I suppose this `Walk` method is in the last version of revel but not on older version which somehow break in our case.

**Pull request merged**
